config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  resources :documents

end

app/models/document.rb
class Document < ActiveRecord::Base

  validates :name, presence: true

  has_attached_file :doc

  validates_attachment_content_type :doc, content_type: [
    "application/pdf",
    "application/msword",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "text/css",
    "application/javascript",
  ]


  def box_viewer
    box_document = generate_box_document
    generate_box_session(box_document['id'])
  end

  def generate_box_document
    response = HTTParty.post('https://view-api.box.com/1/documents',
      headers: {
        'Authorization' => "Token #{ENV['BOX_VIEW_API_KEY']}",
        'Content-Type' => 'application/json',
      },
      body:
      {
        url: doc.url,
        name: doc.name
      }.to_json
    )
  end

  def generate_box_session(document_id)
    session = HTTParty.post('https://view-api.box.com/1/sessions',
      headers: {
        'Authorization' => "Token #{ENV['BOX_VIEW_API_KEY']}",
        'Content-Type' => 'application/json',
      },
      body: {
        document_id: document_id,
        expires_at: 90.days.from_now,
        is_downloadable: true,
      }.to_json
    )

    if session.response.code == '201'
      self.update_column(:box_view_url, session['urls']['view'])
    elsif session.response.code == '202'
      generate_box_session(document_id)
    else
      raise "error while loading, try to upload your doc again"
    end

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)

    if @document.save
      redirect_to document_path(@document)
    else
      render :new
    end
  end



  def show
    @document = Document.find(params[:id])
  end

  private

  def document_params
    params.require(:document).permit(:name, :doc)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_upload.html.slim
= simple_form_for(@document, html: { multipart: true }) do |f|
  p
    = f.input :name, label: 'Title of your document'
    = f.input :doc, label: 'Attach file'
    = f.submit "Upload Document", class:"btn btn-danger"

app/views/documents/index.html.slim
- content_for(:title, 'All Documents')

.container
  .row
    .col-sm-12
      .text-center
        ul.list-inline
          li.small-padded.padded-right= link_to '<i class="fa fa-home"></i>'.html_safe, root_path
          li= link_to '<i class="fa fa-plus"></i>'.html_safe, new_document_path
    - @documents.each do |doc|
      .col-sm-6
        .text-center.small-padded
          h3
            = link_to doc.name.upcase, document_path(doc)

app/views/documents/new.html.slim
- content_for(:title, 'Upload')

.bg-yellow.mini-height
  .container
    .row
      .col-sm-8.col-sm-offset-2
        .padded.margin-space.text-center
          == render 'upload'

app/views/documents/show.html.slim
- content_for(:title, 'Document')

.container
  .row
    .col-sm-12
      .text-center.small-padded
        = link_to '<i class="fa fa-home"></i>'.html_safe, root_path

    .col-sm-12
      .text-center
        - if @document.box_view_url.present?
          .embed-responsive.embed-responsive-4by3
            iframe src=@document.box_view_url class="embed-responsive-item" frameborder="0" allowfullscreen="allowfullscreen"
        - else
          - @document.box_viewer
          p Your document is loading...
          .box_loader

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "Your App name" %></title>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/layouts/application.html.slim
doctype html
  html
    head
      title= "#{yield(:title) || 'Learning By Teaching'} "
    meta name="viewport" content="width=device-width, initial-scale=1">
    = stylesheet_link_tag    "application", media: 'all'
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    = csrf_meta_tags

  body

    = yield

    = javascript_include_tag 'application'
    = yield(:after_js)

app/views/pages/home.html.slim
- content_for(:title, 'Home')

.text-center
  h1 Hello World !

h1 Yo guys !